dist: bionic
language: minimal

addons:
  apt:
    packages:
    - bison
    - flex
    - curl
    - gcc
    - g++
    - make
    - texinfo
    - zlib1g-dev
    - unzip
    - patch
    - xz-utils

script:
  - ./build-djgpp.sh `ls script/ | sort -V | tail -n 1`
