dist: bionic
language: minimal

addons:
  apt:
    packages:
    - bison
    - flex
    - curl
    - gcc
    - g++
    - make
    - texinfo
    - zlib1g-dev
    - unzip
    - patch
    - xz-utils

script:
  - DJGPP_PREFIX=/tmp/djgpp ./build-djgpp.sh `ls script/ | sort -V | tail -n 1`
  - tar -C /tmp -c djgpp | bzip2 -9 > djgpp-linux64-gcc`ls script/ | sort -V | tail -n 1 | sed s/\\.//g`.tar.bz2

cache:
  directories:
    - download
